<?php
/**
 * API coverage report for chaos tests.
 *
 * Walks every .stub.php under ext/async to collect the public API surface,
 * walks _harness/Steps.php to find which API methods step definitions
 * actually invoke, and writes COVERAGE.md showing covered vs uncovered.
 *
 * Heuristic: a method or function is "covered" if its name appears either
 * verbatim in Steps.php (e.g. "->send(", "->close(", "Async\spawn(",
 * "delay(") or in another harness file.
 *
 * Usage:
 *   php fuzzy-tests/_harness/coverage.php
 */

namespace Async\Chaos\Coverage;

const EXT_DIR    = __DIR__ . '/../..';   // ext/async/
const FUZZY_DIR  = __DIR__ . '/..';
const REPORT_OUT = __DIR__ . '/../COVERAGE.md';

/** Extract API surface: returns ['ClassName' => ['method', ...], '_functions' => ['fn', ...]]. */
function collectApi(string $extDir): array {
    $api = ['_functions' => []];
    foreach (glob($extDir . '/*.stub.php') as $stub) {
        $src = file_get_contents($stub);
        // Strip out comments and PHPDoc for cleaner regex
        $clean = preg_replace('!/\*.*?\*/!s', '', $src);
        $clean = preg_replace('!//[^\n]*!', '', $clean);

        // Track current class
        $currentClass = null;
        foreach (explode("\n", $clean) as $line) {
            if (preg_match('/^\s*(?:final\s+|abstract\s+)?(class|interface)\s+([A-Z][A-Za-z0-9_]*)/', $line, $m)) {
                $currentClass = $m[2];
                if ($m[1] === 'interface') {
                    $api['_interfaces'][$currentClass] = true;
                }
                $api[$currentClass] = $api[$currentClass] ?? [];
                continue;
            }
            if ($currentClass !== null) {
                if (preg_match('/^\s*public\s+function\s+([a-zA-Z_][A-Za-z0-9_]*)\s*\(/', $line, $m)) {
                    if (!str_starts_with($m[1], '__')) {
                        $api[$currentClass][] = $m[1];
                    }
                }
            } elseif (preg_match('/^\s*function\s+([a-z_][A-Za-z0-9_]*)\s*\(/', $line, $m)) {
                $api['_functions'][] = $m[1];
            }
        }
    }
    foreach ($api as $k => $v) {
        if ($k === '_interfaces') continue;
        $api[$k] = array_values(array_unique($v));
        sort($api[$k]);
    }
    return $api;
}

/** Read all PHP files under fuzzy-tests/_harness for method/function references. */
function harnessText(string $fuzzyDir): string {
    $buf = '';
    foreach (glob($fuzzyDir . '/_harness/*.php') as $f) {
        $buf .= file_get_contents($f) . "\n";
    }
    return $buf;
}

/** Heuristic test: is this method name referenced by harness code? */
function isMethodCovered(string $haystack, string $name): bool {
    // ->name(  for instance methods,  Class::name(  for statics,  use function …\name; for global fns
    $pattern = '/(->|::|\\\\)' . preg_quote($name, '/') . '\s*\(/';
    if (preg_match($pattern, $haystack)) return true;
    // Direct global function reference
    if (preg_match('/\bAsync\\\\' . preg_quote($name, '/') . '\s*\(/', $haystack)) return true;
    return false;
}

/**
 * Callback-interface methods (CircuitBreakerStrategy, SpawnStrategy, …) are
 * invoked by the C runtime, never by `->method(` in harness code — so the
 * call-site heuristic cannot see them. When the harness defines a class that
 * `implements` the interface, every method it provides IS exercised: the
 * runtime drives them. Treat such methods as covered.
 */
function interfaceImplementedByHarness(string $haystack, string $interface): bool {
    return (bool)preg_match('/\bimplements\b[^{]*\b' . preg_quote($interface, '/') . '\b/', $haystack);
}

/** Method names declared by a harness class (matches `function name(`). */
function harnessDefinesMethod(string $haystack, string $name): bool {
    return (bool)preg_match('/\bfunction\s+' . preg_quote($name, '/') . '\s*\(/', $haystack);
}

function main(): int {
    $api = collectApi(EXT_DIR);
    $haystack = harnessText(FUZZY_DIR);
    $interfaces = $api['_interfaces'] ?? [];
    unset($api['_interfaces']);

    $totalCovered = 0;
    $totalAll = 0;

    $out  = "# Chaos test API coverage\n\n";
    $out .= "Generated by `_harness/coverage.php`. Heuristic: a method/function is\n";
    $out .= "marked **covered** if its name is referenced in any `_harness/*.php` file\n";
    $out .= "(via `->name(`, `::name(`, or `Async\\name(`). This is a lower bound —\n";
    $out .= "indirect calls and complex flows may underreport.\n\n";

    foreach ($api as $entity => $methods) {
        if (empty($methods)) continue;
        // A callback interface implemented by a harness class: its methods are
        // driven by the runtime, so count any the harness actually defines.
        $harnessImpl = isset($interfaces[$entity])
            && interfaceImplementedByHarness($haystack, $entity);
        $covered = 0;
        $rows = [];
        foreach ($methods as $m) {
            $isCov = isMethodCovered($haystack, $m)
                || ($harnessImpl && harnessDefinesMethod($haystack, $m));
            if ($isCov) $covered++;
            $rows[] = ($isCov ? '✓' : '·') . ' `' . $m . '`';
        }
        $totalCovered += $covered;
        $totalAll += count($methods);

        $title = $entity === '_functions' ? 'Async\\\\<function>' : $entity;
        $out .= "## $title — $covered / " . count($methods) . "\n\n";
        $out .= implode("\n", $rows) . "\n\n";
    }

    $pct = $totalAll === 0 ? 0 : round(100 * $totalCovered / $totalAll, 1);
    $summary = "## Summary\n\n**$totalCovered / $totalAll** entries covered ($pct%).\n\n";
    $out = preg_replace('/^# Chaos test API coverage\n\n/', "# Chaos test API coverage\n\n$summary", $out, 1);

    file_put_contents(REPORT_OUT, $out);
    echo "[coverage] wrote " . REPORT_OUT . " — $totalCovered / $totalAll covered ($pct%)\n";
    return 0;
}

exit(main());
