name: True Async Windows Build

on:
  push:
    branches: [build]
  pull_request:
    branches: [build]

jobs:
  WINDOWS:
    name: WINDOWS_X64_ZTS
    runs-on: windows-2022
    timeout-minutes: 50
    env:
      PHP_BUILD_CACHE_BASE_DIR: C:\build-cache
      PHP_BUILD_OBJ_DIR: C:\obj
      PHP_BUILD_CACHE_SDK_DIR: C:\build-cache\sdk
      PHP_BUILD_SDK_BRANCH: php-sdk-2.3.0
      PHP_BUILD_CRT: vs17
      PLATFORM: x64
      THREAD_SAFE: "1"
      INTRINSICS: AVX2
      PARALLEL: -j2
      OPCACHE: "1"
    steps:
      - name: git config
        run: git config --global core.autocrlf false && git config --global core.eol lf

      - name: Checkout php-async repo
        uses: actions/checkout@v4
        with:
          path: async

      - name: Clone php-src (true-async-stable)
        run: |
          git clone --depth=1 --branch=true-async-stable https://github.com/true-async/php-src php-src

      - name: Copy async extension to php-src
        shell: cmd
        run: |
          if not exist php-src\ext\async mkdir php-src\ext\async
          xcopy /E /I /H /Y async php-src\ext\async

      - name: Setup LibUV
        shell: powershell
        run: |
          if (!(Test-Path "C:\vcpkg")) {
            git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
            C:\vcpkg\bootstrap-vcpkg.bat
          }
          C:\vcpkg\vcpkg.exe install libuv:x64-windows

      - name: Setup
        working-directory: php-src
        uses: ./.github/actions/setup-windows

      - name: Build
        working-directory: php-src
        run: .github/scripts/windows/build.bat

      - name: Test
        working-directory: php-src
        run: .github/scripts/windows/test.bat